window.alert("Hello, World!");
document.write("Hello, World!");
var A = "Hello, Welcome to Everyone";
document.write(A);
var message = "Hello, Welcome!";
window.alert(message);
var message = "He said, \"It's a beautiful day!\"";
window.alert(message);
var greeting = "Hello";
var name = "John";
document.write(greeting + ", " + name + "! Welcome to my website.");
var greeting = "Hello";
var name = "Alice";
var message = greeting + ", " + name + "! Welcome to my website.";
document.write(message);
var greeting = "Hello", name = "Charlie", message = "Welcome to my site!";
document.write(name);
var result = 5 + 10;
document.write(result);

